### PR TITLE
Fix #5101 - Update monthly reports for DistrictHeatingWater

### PR DESCRIPTION
**Pull request by jmarrec**
* **Companion PR**:  https://github.com/NREL/OpenStudio/pull/5106

* Fix https://github.com/NREL/OpenStudio/issues/5101

* Note for the name of the Output:Table:Monthly: AFAIK, this is OpenStudio::EndUseFuelType::valueDescription that is used by reporting measures so I made the change as well, perhaps some of them harcoded it to "District Heating", I'm not sure
* `Electricity Peak Demand` was missing Refrigeration EUT

To see the actual changes to the Output:Table:Monthly, just look at https://github.com/NREL/OpenStudio-workflow-gem/pull/149/commits/32f37e2d00c103fd6d59d8573c7134d3ddf83b0a

### CODE REVIEW

**Comment by jmarrec** [comment]
@DavidGoldwasser the companion PR has been merged, can you do this one?

**Comment by kbenne** [comment]
@DavidGoldwasser and @kflemin please take a look at this if you can.

**Review by kflemin — APPROVED** [review]
👍

**Comment by jmarrec** [comment]
@kflemin @DavidGoldwasser can someone merge this one please?

**Review by DavidGoldwasser — APPROVED** [review]

**Pull request merged**
