### PR TITLE
Reporting Measure: passing `model` to `arguments()`

### LINKED ISSUE #93: Pass Model to the arguments method of ReportingMeasure
From @DavidGoldwasser on https://github.com/NREL/OpenStudio/issues/3563#issuecomment-558216922

> A number of users have wanted to access the model in the arguments section of the reporting measures. That does appear to be a gap in functionality as neither the model, IDF, or runner are available in arguments method of reporting measure.

### PR DESCRIPTION
**Pull request by jmarrec**
Fixes #93

Companion PR: https://github.com/NREL/OpenStudio/pull/3796

Untested In OS Application now, I'm hoping I can get CI to build the gem for me so I can test it in the 3796 PR...

I have added a rspec test, which passes with PR3796 though.

### CODE REVIEW

**Comment by nllong** [comment]
@jmarrec  -- can you resolve the conflicts on this?

**Comment by jmarrec** [comment]
@nllong done.

**Comment by nllong** [comment]
> looks good. thanks for adding the test!

Actually, after looking more at the rspec, it looks like this may not be working. I'm seeing errors locally when I run the tests and the CI machine reports the content below. Can you verify that these errors are okay? The "is using the old format where the 'arguments' method does not take model" seem concerning.

```
[15:40:25.121365 ERROR] Reporting Measure at /home/ubuntu/jenkins/workspace/openstudio-workflow-gem_PR-94/spec/files/fast_osw/measures/DencityReports/measure.rb is using the old format where the 'arguments' method does not take model. Please consider updating this to `def arguments(model)`.

[15:40:25.121436 ERROR] wrong number of arguments (1 for 0)

	/home/ubuntu/jenkins/workspace/openstudio-workflow-gem_PR-94/spec/files/fast_osw/measures/DencityReports/measure.rb:17:in `arguments'

	/home/ubuntu/jenkins/workspace/openstudio-workflow-gem_PR-94/lib/openstudio/workflow/util/measure.rb:362:in `apply_measure'

	/home/ubuntu/jenkins/workspace/openstudio-workflow-gem_PR-94/lib/openstudio/workflow/util/measure.rb:109:in `block in apply_measures'

	/home/ubuntu/jenkins/workspace/openstudio-workflow-gem_PR-94/lib/openstudio/workflow/util/measure.rb:67:in `each_index'
```

**Comment by jmarrec** [comment]
The fact that is logs a warning (an error here actually...) is on purpose, because you want to let users know that they are using something deprecated (and out-of-line with the template that would ship with OS 3.x), but it should work with the old method...

I'm rebuilding openstudio locally and will run the tests and try to fix whatever's not working.

**Comment by jmarrec** [comment]
```
Finished in 7 minutes 33 seconds (files took 0.44773 seconds to load)
33 examples, 2 failures

Failed examples:

rspec ./spec/openstudio/workflow/workflow_analysis_spec.rb:851 # OSW Integration should handle weather file throughout the run
rspec ./spec/openstudio/workflow/workflow_analysis_spec.rb:939 # OSW Integration should run an initially empty EPW file
```

**Comment by jmarrec** [comment]
This seem unrelated to this PR:

https://github.com/NREL/OpenStudio-workflow-gem/blob/f598c889d925b2110daaeedfac84a2f94a9f28d1/spec/openstudio/workflow/workflow_analysis_spec.rb#L873-L880

`puts model.get.getOptionalWeatherFile.get.to_s`

```
OS:WeatherFile,
  {723b8b41-fedf-4006-b2ea-df5318b05b7b}, !- Handle
  Golden,                                 !- City
  CO,                                     !- State Province Region
  USA,                                    !- Country
  TMY3,                                   !- Data Source
  724666,                                 !- WMO Number
  39.74,                                  !- Latitude {deg}
  -105.18,                                !- Longitude {deg}
  -7,                                     !- Time Zone {hr}
  1829,                                   !- Elevation {m}
  file:files/USA_CO_Golden-NREL.724666_TMY3.epw, !- Url
  BDF687C1;                               !- Checksum

```


```
[29] workflow(main)> puts workflow_json
{
   "seed_file" : "seb.osm",
   "steps" : 
   [
      {
         "arguments" : {},
         "measure_dir_name" : "OsChangeWeatherFile"
      },
      {
         "arguments" : {},
         "measure_dir_name" : "OsChangeWeatherFile2"
      },
      {
         "arguments" : {},
         "measure_dir_name" : "EpChangeWeatherFile"
      },
      {
         "arguments" : {},
         "measure_dir_name" : "EpChangeWeatherFile2"
      }
   ],
   "weather_file" : "USA_CA_San.Francisco.Intl.AP.724940_TMY3.epw"
}

```

**Comment by jmarrec** [comment]
@nllong does that ring a bell to you per any chance?

https://github.com/NREL/OpenStudio/commit/0b4cf6a7365a48996b20cc05160f9d20980a99f6

https://github.com/NREL/OpenStudio/pull/3401

**Comment by nllong** [comment]
Hmm, this doesn't jog the memory. yeah, `file://` would make sense.

**Comment by jmarrec** [comment]
@nllong ok, develop of this repo has the same problem. I'll open a separate issue. This PR appears to be working correctly already though.

**Comment by nllong** [comment]
@jmarrec -- sounds like this is ready to merge. Any objections to merging?

**Comment by jmarrec** [comment]
No I agree

**Pull request merged**
