### PR TITLE
Osw argument hash

### PR DESCRIPTION
**Pull request by macumber**
@rHorsey @kbenne FYI this was easier than I thought it would be

### CODE REVIEW

**Comment by macumber** [comment]
Do not merge this until after Kyle's demo

**Comment by rHorsey** [comment]
@macumber Looks good to me. We'll plan to merge this tomorrow after the demo?

**Comment by nllong** [comment]
It seems like this breaks the niceness of having arguments as objects, which is the way that rails deals with arguments. What is the use case for this? It looks like it went from 

```
arguments = [
  { 
    name: "some name",
    display_name: "some display name",
    value: 25
  },
  ...
]
```

to 

```
arguments = {
  arg1_value: 1,
  arg2_value: "something else"
}
```

am I missing something?

**Comment by macumber** [comment]
Thanks for looking @nllong, I'll try to explain the thinking:

The arguments method returns a vector of OSArgument objects, these appear as a vector of objects in JSON. These objects include a bunch of properties for each argument (name, displayname, default value, etc).  These properties are needed in the PAT GUI, etc.  

However, the OSW is only needed at measure run time so it does not need all this extra information, it just needs to list what values to set each argument to.  The run signature reflects this as it takes a map of string to OSArgument.  We thought it would be better to make the OSW take a single object for the arguments to 1) make the format more compact and 2) prevent problems with multiple argument values associated with the same argument name key.

**Comment by nllong** [comment]
I see. So the osw is loosing information from the 'other format'. So is the other format the OSA?

Isn't number 2 just dealt with programatically by having the 'name' equal the argument name? Isn't that guaranteed to be unique because the argument names are required to be unique?

**Comment by macumber** [comment]
Yes, other format is OSA

You can have name be the argument name, it is just a little more verbose than it needs to be

**Comment by nllong** [comment]
Ok. It just seems that this creates more of a headache by having two different views of arguments in two different file formats. 

Maybe the issue is that we have datapoint.json, analysis.json, osa.json, osw.json, and probably a couple other formats for PAT 2.0.

**Comment by macumber** [comment]
Yeah its kind of a bummer to have so many formats, I feel like hash is the way to go with OSW, I'm open to other comments, I guess we just need a vote.  But we do need to resolve this soon.  @kbenne @rHorsey can you weigh in?

**Comment by macumber** [comment]
PS: this matters because OSW is a format that users may hand write, we might think about asking a potential user or two?

**Comment by rHorsey** [comment]
Oh wait, I just read the above thread. Let's make a call one way or another tomorrow at our meeting @macumber @nllong @kbenne

**Comment by nllong** [comment]
merge it. The result format just needs to be able to reverse translate to the data point so that we can post the data to the server.

**Comment by rHorsey** [comment]
Merging

**Pull request merged**
